### PR TITLE
Fix overlay colors calculation

### LINKED ISSUE #44: Overlays are no longer colored by a generated value from their names
From: https://single-spa.js.org/docs/devtools

>       color: "#000", // the default for this is actually based on the app's name, so it's dynamic. can be a hex or a CSS color name
      background: "#000", // the default for this is actually based on the app's name, so it's dynamic. can be a hex or a CSS color name

These seem to always be black here: https://react.microfrontends.app/people

### PR DESCRIPTION
**Pull request by filoxo**
Fix overlay colors calculation by removing non-alphanumeric characters that would cause parseInt to return NaN.

Resolves #44 

I tested this on the react.microfrontends.app site. 

Screen Shot 2020-04-16 at 5 08 16 PM

### CODE REVIEW

File: src/inspected-window-helpers/overlay-helpers.js [hunk 1]
```diff
@@ -130,9 +130,10 @@ export function setupOverlayHelpers() {
   }
 
   function getColorFromString(string, opacity = 0.4) {
+    const cleanStr = string.replace(/[^0-9a-z]/gi, "");
```
Comment (joeldenning) [inline src/inspected-window-helpers/overlay-helpers.js:133]: This regex doesn't keep capitalized letters, and also doesn't keep non-ascii characters that might be used by those who speak other languages.

We should at least do `0-9a-zA-Z`, but are there any other characters we should allow?

Comment (filoxo) [reply src/inspected-window-helpers/overlay-helpers.js:133]: The `i` flag means its case insensitive, and does keep capitalized letters. 

```js
"@Some-org/module".replace(/[^0-9a-z]/gi, "") // returns "Someorgmodule"
```

I'm not sure how parseInt handles non-ascii characters but I vote for solving that when it comes up.

Comment (filoxo) [reply src/inspected-window-helpers/overlay-helpers.js:133]: Let me take that back. Now that we're sure that we have at least a few users in China (quiankun) maybe it should be solved now. I'll investigate.

Comment (filoxo) [reply src/inspected-window-helpers/overlay-helpers.js:133]: Perhaps using [toascii](https://github.com/zipavlin/toascii-js) to replace non-ascii in a determinate way, and that way the colors output are also consistent.

Comment (TheMcMurder) [reply src/inspected-window-helpers/overlay-helpers.js:133]: I like the idea of replacing the nonascii characters when possible with a fallback.

Comment (filoxo) [reply src/inspected-window-helpers/overlay-helpers.js:133]: Or maybe just converting the ascii chars to charCode, which always return an integer and then everything is good to go. https://stackoverflow.com/questions/94037/convert-character-to-ascii-code-in-javascript

Mostly just writing down ideas before getting to it later tonight.

Comment (joeldenning) [reply src/inspected-window-helpers/overlay-helpers.js:133]: ah i missed the `i` flag on the regex. Yeah this is fine then - if we can handle other characters that is good too. but this looks good to me

File: src/inspected-window-helpers/overlay-helpers.js [hunk 2]
```diff
@@ -130,9 +130,14 @@ export function setupOverlayHelpers() {
   }
 
   function getColorFromString(string, opacity = 0.4) {
+    const cleanStr = string
+      .split("")
+      .map(l => (/[^0-9a-z]/gi.test(l) ? l.charCodeAt(0) : l)) // replace non-ascii with charCode integer
```
Comment (filoxo) [inline src/inspected-window-helpers/overlay-helpers.js:135]: Here is a screenshot of the results of the appNames I tested: 

Screen Shot 2020-04-17 at 10 30 42 AM
